version: '3'

# cada serviço é um container
services:
  app:
    # caminho para a Dockerfile - no caso, está na raiz
    build: .
    # wait for db for 40s max, then execute start.sh
    command: wait-for db:3306 -t 40 -- ./start.sh
    ports:
      - 8000:3000
    volumes:
      - .:/home/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database:/var/lib/mysql
